#! /bin/bash

json=$(< /dev/stdin)

# This script requires `jq` in $PATH: http://stedolan.github.io/jq/
name=$(jq '.hook.name' <<< $json)
value=$(( $(jq '.hook.config.value' <<< $json) + 1 ))

cat <<EOF
{
  "hook": {
    "configuration": {
      "update": {
        "value": $value
      }
    }
  },
  "node": {
    "metadata": {
      "update": {
        $name: $value
      }
    }
  }
}
EOF
