#! /bin/bash

set -e

json=$(< /dev/stdin)

value=1

cat <<EOF
{
  "hook": {
    "configuration": {
      "update": {
        "node-install-finished": $value
      }
    }
  },
  "node": {
    "metadata": {
      "update": {
        "last_hook_execution": "node-install-finished"
      }
    }
  }
}
EOF
